# Copyright (C) 2024 psionicprjkt

name: build-kernelsu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Android Build Environment
        run: |
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh

      - name: Setup Repository & Resources
        run: |
          git config --global user.name "officialputuid" && git config --global user.email officialputuid@hack.id
          git clone --recursive --depth=1 https://officialputuid:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO_PRIVATE }} -b ${{ secrets.GH_BRANCH_PRIVATE }} salaa && cd salaa
          git clone --depth=1 https://github.com/psionicprjkt/aarch64-linux-android-4.9 arm64 && git clone --depth=1 https://github.com/psionicprjkt/arm-linux-androideabi-4.9 arm32
          wget --quiet https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz -O "aosp-clang.tar.gz"
          mkdir clang && tar -xf aosp-clang.tar.gz -C clang && rm -f aosp-clang.tar.gz

      - name: Setup Version
        run: |
          cd salaa
          v=$(cat version)
          d="arch/arm64/configs/salaa_defconfig"
          sed -i "s/\(CONFIG_LOCALVERSION=\"-psionic-kernelsu-\).*\"/\1$v\"/" $d
          patch -p1 <*.patch

      - name: Check Version Kernel
        run: |
          cd salaa
          kv=$(make kernelversion 2>/dev/null)
          d="arch/arm64/configs/salaa_defconfig"
          echo "Kernel Version: $kv"
          echo "Local Version: $(grep CONFIG_LOCALVERSION= $d | cut -d '"' -f2)"

      - name: Setup Build Kernel
        run: cd salaa && . build-ksu.sh

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"
          echo "VERSION_KERNEL=$(cat version)" >> "$GITHUB_ENV"

      - name: Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "KernelSU"
          prerelease: false
          title: psionic-kernel-salaa-${{ env.RELEASE_DATE }}-${{ env.VERSION_KERNEL }}-KernelSU
          files: |
            salaa/AnyKernel/psionic-kernel-salaa*
