name: build-kernelsu-ok

on:
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'RMX2151'
      MANIFEST_BRANCH:
        required: true
        default: '14-ksu'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Android Build Environment
        run: |
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup SSH Keys
        if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') }}
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}          
      - name: Setup Repository & Resources
        run: |
          git config --global user.name "gofaraway71" && git config --global user.email aalbatron@google.com
          git clone --depth=1 https://github.com/albatron34000/android_kernel_realme_salaa -b android-14 mt6785
          cd mt6785
          rm -rf KernelSU
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          git clone --depth=1 https://github.com/psionicprjkt/aarch64-linux-android-4.9 arm64 && git clone --depth=1 https://github.com/psionicprjkt/arm-linux-androideabi-4.9 arm32
          wget --quiet https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz -O "clang.tar.gz"
          mkdir clang && tar -xf clang.tar.gz -C clang && rm -f clang.tar.gz
      - name: Setup Build Kernel
        run: cd mt6785 && bash build-ksu.sh
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}
        

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: mt6785/AnyKernel/gofaraway*
          name: psionic_salaa_KernelSU
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
            Device: ${{ github.event.inputs.DEVICE_NAME }}
            Target: salaa_KernelSU
            Version:Android14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
